### ISSUE TITLE
Internal Server Error by searching "http://ceur-ws.org/"

### ISSUE THREAD

**Issue by SimonBruns** [WolfgangFahl/ProceedingsTitleParser#19]

**Comment by WolfgangFahl** [comment]
see log
`in parseAll
    title=Title(eventTitle,self.ptp.grammar,dictionary=self.dictionary)
  File "/home/wf/source/python/ProceedingsTitleParser/ptp/titleparser.py", line 174, in __init__
    line=line.replace(blanktoken,blankless)
AttributeError: 'NoneType' object has no attribute 'replace'
127.0.0.1 - - [10/Jul/2020 11:11:37] "GET /parse?titles=http%3A%2F%2Fceur-ws.org%2F HTTP/1.1" 500 -
`
